### ISSUE TITLE
Consider to upgrade to the latest `kopf`

### ISSUE THREAD

**Issue by haoxins** [lsst-sqre/strimzi-registry-operator#48]
I noticed that we are using an old version of `kopf` (`0.21`).
And this version depends on some deprecated packages.
So, is there any plan to upgrade to the latest `kopf`?

**Comment by jonathansick** [comment]
You're quite right! I'll add this as a maintenance priority and hopefully we can get out a refreshed version ASAP.

**Comment by jonathansick** [comment]
We took care of this in #56 and it's now available in the 0.5.0 release.
